### ISSUE TITLE
Limit output to only woff2?

### ISSUE THREAD

**Issue by zoaha** [jaywcjlove/svgtofont#238]
Is it possible to limit the font outputs to ONLY woff2?

This works for only generating the `.css` instead of `.less, .sass, ....`:
```
	css: {
		output: "output",
		include: "\\.(css)$"
	}
```

Is there something similar for the font files?
I only need woff2.

Ideally generating:
```css
@font-face {
  font-family: "myIcons";
  src: url("myIcons.woff") format("woff2")
}
```
