### ISSUE TITLE
是否有方法可以指定生成的每个图标的 unicode 编码

### ISSUE THREAD

**Issue by netcore-jroger** [jaywcjlove/svgtofont#260]
如题。

另外，生成的CSS文件中的 `content` 属性值为什么不使用十六进制的字符串（_是否可以提供一个配置项_）？：
```css
.icon-header-icon-homepage:before {
  content: "\e950";
}
```

另外，是否考虑支持从 IcoMoon 导出的 `selection.json` 中提取 svg paths 生成字体？
