### ISSUE TITLE
Set a font size to the generated?

### ISSUE THREAD

**Issue by vitto** [jaywcjlove/svgtofont#52]
It would be nice to have the possibility to set the `font-size` on the css generated before build it, this would avoid me to change it manually after the build.

So instead to have `16px` every time:

```css
.iconfont {
  font-family: "svgtofont-iconfont" !important;
  font-size: 16px;
  ...
}
```

Have the possibility to set a custom `font-size`:

```css
.iconfont {
  font-family: "svgtofont-iconfont" !important;
  font-size: 24px; /* material icons like font-size */
  ...
}
```
